### ISSUE TITLE
Crash when opening any file

### ISSUE THREAD

**Issue by Vojtak42** [AcK77/TTGames-Explorer-Rebirth#7]
```
Informace o vyvolání ladění JIT najdete na konci této zprávy,
nikoli v tomto dialogovém okně.

************** Text výjimky **************
System.IO.InvalidDataException: 0000003a
   at TTGamesExplorerRebirthLib.Formats.FT2.Deserialize(Byte[] buffer) in C:\Users\Ac_K\Desktop\Projects\TTGamesExplorerRebirth\src\TTGamesExplorerRebirthLib\Formats\FT2.cs:line 79
   at TTGamesExplorerRebirthLib.Formats.FT2..ctor(Byte[] buffer) in C:\Users\Ac_K\Desktop\Projects\TTGamesExplorerRebirth\src\TTGamesExplorerRebirthLib\Formats\FT2.cs:line 44
   at TTGamesExplorerRebirthUI.Forms.FontForm..ctor(String filePath, Byte[] fileBuffer) in C:\Users\Ac_K\Desktop\Projects\TTGamesExplorerRebirth\src\TTGamesExplorerRebirthUI\Forms\FontForm.cs:line 30
   at TTGamesExplorerRebirthUI.Helper.OpenFileInternal(String gameFolderPath, String path, Byte[] fileBuffer, Object archiveFile) in C:\Users\Ac_K\Desktop\Projects\TTGamesExplorerRebirth\src\TTGamesExplorerRebirthUI\Helper.cs:line 128
   at TTGamesExplorerRebirthUI.Forms.MainForm.DarkListView1_DoubleClick(Object sender, EventArgs e) in C:\Users\Ac_K\Desktop\Projects\TTGamesExplorerRebirth\src\TTGamesExplorerRebirthUI\Forms\MainForm.cs:line 305
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)


************** Načtená sestavení **************
System.Private.CoreLib
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Private.CoreLib.dll
----------------------------------------
TTGamesExplorerRebirthUI
    Verze sestavení: 1.0.0.0
    Umístění: C:\Users\Vojta\Documents\TTGamesExplorerRebirth_v0.1_x64\TTGamesExplorerRebirthUI.dll
----------------------------------------
System.Runtime
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\System.Windows.Forms.Primitives.dll
----------------------------------------
DarkUI
    Verze sestavení: 2.0.2.0
    Umístění: C:\Users\Vojta\Documents\TTGamesExplorerRebirth_v0.1_x64\DarkUI.dll
----------------------------------------
System.ComponentModel.Primitives
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.InteropServices.dll
----------------------------------------
System.Threading
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Threading.dll
----------------------------------------
System.Drawing.Common
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Collections.dll
----------------------------------------
Microsoft.Win32.Primitives
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Threading.Thread.dll
----------------------------------------
Accessibility
    Verze sestavení: 4.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.ComponentModel.TypeConverter.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Numerics.Vectors.dll
----------------------------------------
System.ObjectModel
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.ObjectModel.dll
----------------------------------------
System.Memory
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Memory.dll
----------------------------------------
System.Resources.Extensions
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\System.Drawing.dll
----------------------------------------
System.Runtime.Loader
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\cs\System.Windows.Forms.resources.dll
----------------------------------------
System.Collections.NonGeneric
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Collections.NonGeneric.dll
----------------------------------------
System.Text.Json
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Text.Json.dll
----------------------------------------
System.Text.Encoding.Extensions
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Text.Encoding.Extensions.dll
----------------------------------------
System.Text.Encodings.Web
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.Intrinsics.dll
----------------------------------------
System.Private.Uri
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Private.Uri.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Linq
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Linq.dll
----------------------------------------
System.Security.Cryptography
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Security.Cryptography.dll
----------------------------------------
System.IO.FileSystem.Watcher
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.IO.FileSystem.Watcher.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Threading.Overlapped
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Threading.Overlapped.dll
----------------------------------------
TTGamesExplorerRebirthLib
    Verze sestavení: 1.0.0.0
    Umístění: C:\Users\Vojta\Documents\TTGamesExplorerRebirth_v0.1_x64\TTGamesExplorerRebirthLib.dll
----------------------------------------
System.Diagnostics.StackTrace
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Verze sestavení: 8.0.0.0
    Umístění: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.IO.MemoryMappedFiles.dll
----------------------------------------

************** Ladění JIT **************


```

**Comment by AcK77** [comment]
What file are you trying to open? From which game?

**Comment by Vojtak42** [comment]
.FT2 font files but i am not even able to open .dat files, i had to use quickbms

**Comment by AcK77** [comment]
Only few games are supported, maybe the DAT or FT2 files are from an unsupported game, but if you don’t tell me which game it is, I can’t try to fix things…

**Comment by Vojtak42** [comment]
I've edited the message within about a minute of sending but if you're viewing it in mail, then i am sorry. It's Marvel's Super heroes 2
